# Task-1

In [65]:
import pandas as pd

In [66]:
df=pd.read_csv('titanic.csv')

In [67]:
#show a first five column
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [68]:
#show a last five column
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [69]:
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [70]:
#info about how many column, null values, dtype
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    str
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 116.9 KB

In [71]:
#count passenger: 891  passenger in titanic dataset
len(df)

891

In [72]:
#rate for survied column : 0.3338 rate of survived column
df['survived'].mean()

np.float64(0.3838383838383838)

In [73]:
#rate for both female and male : 0.742038 rate of female and 0.188908 rate of male
df.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [74]:
#rate of pclass 
df.groupby('pclass')['survived'].mean()
# class 1 rate:0.629630
# class 2 rate:0.472826
# class 3 rate:0.242363

pclass
1    0.629630
2    0.472826
3    0.242363
Name: survived, dtype: float64

In [75]:
#average of age column
df['age'].mean()

np.float64(29.69911764705882)

In [76]:
#minimum age
df['age'].min()

np.float64(0.42)

In [77]:
#maximum age
df['age'].max()

np.float64(80.0)

In [78]:
#the average fare paid in each class
df.groupby('pclass')['fare'].mean()

pclass
1    84.154687
2    20.662183
3    13.675550
Name: fare, dtype: float64

In [79]:
#survived rate of children
children = df[df["age"] < 18] 
child_survival_rate = children["survived"].mean()

In [80]:
#count a children which age<18
ch=df[df["age"]<18]
len(ch)

113

In [81]:
#count by values in emabarked column
df["embarked"].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [82]:
#count a missing values in age column
df["age"].isnull().sum()

np.int64(177)

In [83]:
# the survival rate for women in 1st class
df[(df["sex"]=='female') & (df["pclass"]==1)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [84]:
# the survival rate for men in 3rd class
df[(df["sex"]=="male") & (df["pclass"]==3)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [85]:
# the average family size on board
(df['sibsp']+df['parch']).mean()

np.float64(0.9046015712682379)

In [86]:

df["family_members"] = df["sibsp"] + df["parch"] 
alone = df[df["family_members"] == 0] 
with_family = df[df["family_members"] > 0] 
alone_survival = alone["survived"].mean() 
family_survival = with_family["survived"].mean() 
print("Survival rate of travelling alone:", alone_survival) 
print("Survival rate of travelling with family:", family_survival)

Survival rate of travelling alone: 0.30353817504655495
Survival rate of travelling with family: 0.5056497175141242

In [87]:
#The Titanic dataset shows that survival differed across passenger groups, particularly by sex and passenger class. 
#The Pandas groupby(), filtering, mean(), value_counts(), and missing-data methods were used to answer the questions.

# Task-2

In [88]:
#confirm age column it's have any null values or not
df['age'].isna().sum()

np.int64(177)

In [89]:
#Strategy 1 — drop: remove rows with missing age. How many rows remain? What did the mean age become?
df_drop = df.dropna(subset=["age"])

print("len of raw:", len(df_drop))
print("Mean age:", df_drop["age"].mean())
print("Standard deviation:", df_drop["age"].std())

len of raw: 714
Mean age: 29.69911764705882
Standard deviation: 14.526497332334042

In [90]:
#Strategy 2 — mean fill: fill missing ages with the overall mean age.
#Check what happens to the standard deviation, and explain why it changes.
df_mean = df.copy()

df_mean["age"] = df_mean["age"].fillna(df_mean["age"].mean())

print("Mean age:", df_mean["age"].mean())
print("Standard deviation:", df_mean["age"].std())

Mean age: 29.69911764705882
Standard deviation: 13.002015226002882

In [91]:
# Strategy 3 — group fill: fill each missing age with the median age of passengers in the same class and sex.
df_group = df.copy()

df_group["age"] = df_group.groupby(
    ["pclass", "sex"]
)["age"].transform(lambda x: x.fillna(x.median()))

print("Mean age:", df_group["age"].mean())
print("Standard deviation:", df_group["age"].std())

Mean age: 29.11242424242424
Standard deviation: 13.304424074688162

In [92]:
comparison = pd.DataFrame({
    "Strategy": [
        "Drop missing ages",
        "Mean fill",
        "Class + Sex median fill"
    ],
    "Mean Age": [
        df_drop["age"].mean(),
        df_mean["age"].mean(),
        df_group["age"].mean()
    ],
    "Standard Deviation": [
        df_drop["age"].std(),
        df_mean["age"].std(),
        df_group["age"].std()
    ]
})

print(comparison)

                  Strategy   Mean Age  Standard Deviation
0        Drop missing ages  29.699118           14.526497
1                Mean fill  29.699118           13.002015
2  Class + Sex median fill  29.112424           13.304424

In [93]:
df_mean.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [94]:
df_group.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

# Task-3

The three missing-age strategies each have different advantages and disadvantages. Dropping missing ages is simple and avoids adding artificial values, but it removes about 20% of the passengers from the age analysis. Mean filling keeps all passengers but reduces the variation because every missing age receives the same value. Group median filling is more representative because it uses the passenger's class and sex when estimating the missing age. For this dataset, I would choose group median filling because it keeps all rows while using more relevant information than a single overall mean. There is no single correct strategy because the best choice depends on the goal; for example, dropping rows may be reasonable when only a small number of values are missing, while group-based imputation may be better when preserving the dataset is important. Clearly documenting an imputation method is important because hiding that a large portion of the data was changed could make the analysis misleading and reduce trust in the results.

In [95]:
passanger=df[(df['sex']=='female')&((df['pclass']==1) | (df['pclass']==2)) & (df['age']<30) ]
#This filter selects female passengers under 30 in 1st or 2nd class and calculates their survival rate.

In [96]:
len(passanger)

71

In [97]:
passanger['survived'].mean()

np.float64(0.9295774647887324)

In [98]:
df[df["survived"] == 1].sort_values("age", ascending=False).head(10)[["sex", "pclass", "age", "fare"]]
#The table shows the 10 oldest passengers who survived, including their sex, class, age, and fare.

        sex  pclass   age      fare
630    male       1  80.0   30.0000
275  female       1  63.0   77.9583
483  female       3  63.0    9.5875
570    male       2  62.0   10.5000
829  female       1  62.0   80.0000
587    male       1  60.0   79.2000
366  female       1  60.0   75.2500
195  female       1  58.0  146.5208
268  female       1  58.0  153.4625
11   female       1  58.0   26.5500

In [99]:
bottom_ten=df['fare'].quantile(0.90)
top_ten=df['fare'].quantile(0.10)

In [100]:
b_ten=df[df['fare']<=bottom_ten]

In [101]:
b_ten

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_members
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,3
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0

In [102]:
t_ten=df[df['fare']>=top_ten]

In [103]:
t_ten

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_members
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,3
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0

In [104]:
t_ten['survived'].mean()

np.float64(0.410958904109589)

In [105]:
b_ten['survived'].mean()
#The survival rates of the top and bottom 10% fare groups can be compared to see how survival differed between passengers paying the highest and lowest fares.

np.float64(0.34328358208955223)

In [106]:
df.sort_values(['pclass','fare'], ascending=[True, False])
#The dataset is sorted with 1st class first, followed by 2nd and 3rd class, while the highest fare appears first within each class.

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_members
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True,0
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False,1
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True,0
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False,5
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,0,3,male,20.0,0,0,4.0125,C,Third,man,True,NaN,Cherbourg,no,True,0
179,0,3,male,36.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True,0
271,1,3,male,25.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,yes,True,0
302,0,3,male,19.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True,0
597,0,3,male,49.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True,0

In [107]:
df[['fare','age']].describe()
#The age column has fewer valid observations than the total number of passengers because some ages are missing.

             fare         age
count  891.000000  714.000000
mean    32.204208   29.699118
std     49.693429   14.526497
min      0.000000    0.420000
25%      7.910400   20.125000
50%     14.454200   28.000000
75%     31.000000   38.000000
max    512.329200   80.000000

In [108]:
df['pclass'].value_counts()
#The dataset contains more passengers in 3rd class than in 1st or 2nd class.

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [109]:
df['embarked'].value_counts()
#Southampton is the most common embarkation port in the dataset.

embarked
S    644
C    168
Q     77
Name: count, dtype: int64